databases:
  - name: tech-inshight-db
    databaseName: tech_inshight
    user: tech_inshight_user
    plan: free

services:
  - type: web
    name: tech-inshight
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Blog_App.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tech-inshight-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
